/* ============================================================================
   ladder.js  —  THE MASTER LADDER (single source of truth for the site)
   ----------------------------------------------------------------------------
   This file declares two globals used across the site:
     • LADDER      — every rung, price-descending. The whole flip mechanic.
     • TIER_META   — tier → {css class, band label, emoji} display map.

   LOAD ORDER (in index.html): coins.js → ladder.js → app.js  (all `defer`).
   These are plain classic-script `const`s, so they are visible to app.js as
   long as this file executes BEFORE app.js. Do NOT add `export` / `type=module`.

   HARD RULES (do not break — see Flipper List rules):
     RULE 1 — UNIQUE PRICES. No two rungs may share a price. A flip fires when a
              coin crosses a price; duplicates collapse the flip event. Before
              adding a rung, check its price against the whole list.
     — Prices are strictly DESCENDING, top to bottom.
     — `tier` must be one of: heavyweight | snack | absurd_floor | void
       (these keys must exist in TIER_META below).
     — `featured: true` marks a ⭐ banger flip.

   NOTE: `tier: 'snack'` is the internal key for the "Real Life" tier
   (label lives in TIER_META). Legacy name; don't rename without touching
   every `tier` value below and the TIER_META key together.
   ========================================================================== */

const LADDER = [
    { price: 1000000000, name: 'a Powerball jackpot (the advertised one)', tier: 'heavyweight', category: 'status' },
    { price: 300000000, name: "a billionaire's superyacht", tier: 'heavyweight', category: 'status' },
    { price: 100000000, name: 'a single painting at auction', tier: 'heavyweight', category: 'status' },
    { price: 30000000, name: 'a new private jet', tier: 'heavyweight', category: 'status' },
    { price: 8000000, name: 'a 30-second Super Bowl ad', tier: 'heavyweight', category: 'status' },
    { price: 5000000, name: "a billionaire's doomsday bunker", tier: 'heavyweight', category: 'status' },
    { price: 3000000, name: "a nurse's entire working life", tier: 'heavyweight', category: 'extraction' },
    { price: 2600000, name: "a teacher's whole 40-year career", tier: 'heavyweight', category: 'extraction', featured: true },
    { price: 1500000, name: 'a comfortable retirement (the real number)', tier: 'heavyweight', category: 'extraction' },
    { price: 1000000, name: 'a million dollars', tier: 'heavyweight', category: 'status' },
    { price: 600000, name: 'a ticket to space', tier: 'heavyweight', category: 'status' },
    { price: 500000, name: 'your own private island', tier: 'heavyweight', category: 'status' },
    { price: 450000, name: 'a year of full household staff', tier: 'heavyweight', category: 'status' },
    { price: 415000, name: 'a paid-off house, free and clear', tier: 'heavyweight', category: 'extraction' },
    { price: 390000, name: 'a Rolls Royce Ghost (fully optioned)', tier: 'heavyweight', category: 'status' },
    { price: 380000, name: 'a thoroughbred racehorse (Keeneland average yearling)', tier: 'heavyweight', category: 'status' },
    { price: 350000, name: 'a Rolls Royce Ghost (base, new)', tier: 'heavyweight', category: 'status' },
    { price: 315000, name: 'the cost of raising one child to age 18 (USDA estimate)', tier: 'heavyweight', category: 'extraction' },
    { price: 300000, name: 'a used Cessna Citation (entry-level private jet)', tier: 'heavyweight', category: 'status' },
    { price: 280000, name: 'one year of 24/7 personal security detail', tier: 'heavyweight', category: 'status' },
    { price: 258000, name: 'a Lamborghini Urus (base, new)', tier: 'heavyweight', category: 'status' },
    { price: 240000, name: 'a Lamborghini Huracán (entry, new)', tier: 'heavyweight', category: 'status' },
    { price: 220000, name: 'a Ferrari Roma (base, new)', tier: 'heavyweight', category: 'status' },
    { price: 180000, name: 'a gold-plated bathtub (bespoke commission)', tier: 'heavyweight', category: 'status' },
    { price: 170000, name: "a forgettable abstract painting at Christie's", tier: 'heavyweight', category: 'status' },
    { price: 160000, name: 'one year at Phillips Exeter Academy (boarding)', tier: 'heavyweight', category: 'status' },
    { price: 150000, name: 'a full Beverly Hills plastic surgery makeover', tier: 'heavyweight', category: 'status' },
    { price: 140000, name: 'one year of luxury nursing home (private room)', tier: 'heavyweight', category: 'status' },
    { price: 130000, name: 'a full gestational surrogacy in the USA', tier: 'heavyweight', category: 'extraction' },
    { price: 120000, name: 'a live-in nanny (NYC)', tier: 'heavyweight', category: 'extraction' },
    { price: 115000, name: 'a Porsche 911 Carrera (base, new)', tier: 'heavyweight', category: 'status' },
    { price: 110000, name: 'a gold toilet (18-karat, functional)', tier: 'heavyweight', category: 'status' },
    { price: 90000, name: 'full-mouth dental implants (all teeth)', tier: 'heavyweight', category: 'extraction' },
    { price: 87000, name: 'one year at Harvard (full cost of attendance)', tier: 'heavyweight', category: 'status', featured: true },
    { price: 75000, name: 'a full luxury kitchen remodel (high-end suburban)', tier: 'heavyweight', category: 'status' },
    { price: 60000, name: 'a down payment on a house', tier: 'heavyweight', category: 'extraction' },
    { price: 52000, name: 'a used Porsche 911 (decent year)', tier: 'heavyweight', category: 'status' },
    { price: 48000, name: 'an average new car (industry average)', tier: 'heavyweight', category: 'status' },
    { price: 45000, name: 'a full IVF package (3 cycles)', tier: 'heavyweight', category: 'extraction', featured: true },
    { price: 43000, name: 'an epic bachelor Vegas weekend (party of 12)', tier: 'heavyweight', category: 'status' },
    { price: 40000, name: 'a Tesla Model 3', tier: 'heavyweight', category: 'status' },
    { price: 35000, name: 'one year of NYC private preschool', tier: 'heavyweight', category: 'status' },
    { price: 30000, name: 'a wedding photographer (high-end with video)', tier: 'heavyweight', category: 'status' },
    { price: 25000, name: 'a new compact car', tier: 'heavyweight', category: 'status' },
    { price: 22000, name: 'an average wedding (small, intimate)', tier: 'heavyweight', category: 'status' },
    { price: 20000, name: 'an engagement ring (nicer)', tier: 'heavyweight', category: 'status' },
    { price: 18000, name: 'a used motorcycle (mid-tier touring)', tier: 'heavyweight', category: 'status' },
    { price: 16000, name: 'one year of average US daycare', tier: 'heavyweight', category: 'extraction', featured: true },
    { price: 14000, name: 'two weeks at a luxury all-inclusive resort', tier: 'heavyweight', category: 'status' },
    { price: 13500, name: 'one year of state college tuition (in-state)', tier: 'heavyweight', category: 'extraction' },
    { price: 12000, name: 'a Hermès Birkin bag', tier: 'heavyweight', category: 'status' },
    { price: 10000, name: 'an engagement ring (modest)', tier: 'heavyweight', category: 'status' },
    { price: 8500, name: 'one year of public university tuition (in-state)', tier: 'heavyweight', category: 'extraction' },
    { price: 8300, name: 'one year of federal income tax for a $75K single earner', tier: 'heavyweight', category: 'extraction', featured: true },
    { price: 7500, name: 'a rhinoplasty (nose job)', tier: 'heavyweight', category: 'status' },
    { price: 6500, name: 'a BBL (Brazilian butt lift)', tier: 'heavyweight', category: 'status' },
    { price: 6000, name: 'a used car (rough condition)', tier: 'heavyweight', category: 'status' },
    { price: 5800, name: 'a Super Bowl ticket (nosebleeds)', tier: 'heavyweight', category: 'status', featured: true },
    { price: 5738, name: "one year of FICA payroll taxes for a $75K earner (you'll never see it back)", tier: 'heavyweight', category: 'extraction' },
    { price: 5500, name: 'a bottle of Pappy Van Winkle 23', tier: 'heavyweight', category: 'status', featured: true },
    { price: 5000, name: 'a full Invisalign treatment', tier: 'heavyweight', category: 'status' },
    { price: 4800, name: 'a Lambo wheel rim', tier: 'heavyweight', category: 'status' },
    { price: 3500, name: 'a mountain bike', tier: 'heavyweight', category: 'status' },
    { price: 3200, name: 'a C-section copay', tier: 'heavyweight', category: 'extraction', featured: true },
    { price: 3000, name: 'one year of US median property tax', tier: 'heavyweight', category: 'extraction' },
    { price: 2800, name: 'one year of advisor fees on $280K (1% AUM)', tier: 'heavyweight', category: 'extraction' },
    { price: 2600, name: 'a coffin (mid-range)', tier: 'heavyweight', category: 'extraction' },
    { price: 2500, name: 'an epidural during birth', tier: 'heavyweight', category: 'extraction', featured: true },
    { price: 2400, name: 'a CrossFit annual membership', tier: 'heavyweight', category: 'extraction' },
    { price: 2200, name: 'a LASIK eye (per eye)', tier: 'heavyweight', category: 'status' },
    { price: 2100, name: 'a sterilization procedure (out of pocket)', tier: 'heavyweight', category: 'extraction' },
    { price: 2000, name: 'a decent laptop', tier: 'heavyweight', category: 'status' },
    { price: 1800, name: 'an uninsured ER visit (minor)', tier: 'heavyweight', category: 'extraction' },
    { price: 1650, name: 'a veneer (per tooth)', tier: 'heavyweight', category: 'status' },
    { price: 1500, name: 'annual car insurance (cheap)', tier: 'heavyweight', category: 'extraction' },
    { price: 1400, name: 'a new gaming console', tier: 'heavyweight', category: 'status' },
    { price: 1300, name: 'an IUD insertion (out of pocket)', tier: 'heavyweight', category: 'extraction' },
    { price: 1250, name: 'a root canal', tier: 'heavyweight', category: 'extraction' },
    { price: 1200, name: 'a year of college textbooks', tier: 'heavyweight', category: 'extraction' },
    { price: 1150, name: 'a CoolSculpting session', tier: 'heavyweight', category: 'status' },
    { price: 1100, name: 'a vasectomy', tier: 'heavyweight', category: 'extraction', featured: true },
    { price: 1050, name: 'a dental crown', tier: 'heavyweight', category: 'extraction' },
    { price: 1025, name: 'a funeral plot (cheap)', tier: 'heavyweight', category: 'extraction' },
    { price: 1000, name: 'one year of mutual fund expense ratios on $100K (1%)', tier: 'heavyweight', category: 'extraction' },
    { price: 950, name: 'a cremation (basic)', tier: 'snack', category: 'extraction' },
    { price: 900, name: 'a weekend Airbnb', tier: 'snack', category: 'status' },
    { price: 880, name: 'one year of premium pet insurance', tier: 'snack', category: 'extraction' },
    { price: 875, name: "one month's rent (small midwest town)", tier: 'snack', category: 'extraction' },
    { price: 850, name: 'one year of average insurance copays', tier: 'snack', category: 'extraction' },
    { price: 750, name: "a wedding band (men's, plain)", tier: 'snack', category: 'status' },
    { price: 650, name: 'a used iPhone', tier: 'snack', category: 'status' },
    { price: 530, name: 'one month of health insurance (unsubsidized ACA, single adult)', tier: 'snack', category: 'extraction' },
    { price: 500, name: 'one annuity surrender charge (5% on $10K)', tier: 'snack', category: 'extraction' },
    { price: 425, name: 'a round-trip domestic flight', tier: 'snack', category: 'status' },
    { price: 415, name: 'a wisdom tooth removal (per tooth)', tier: 'snack', category: 'extraction' },
    { price: 410, name: 'a bottle of Macallan 18', tier: 'snack', category: 'status' },
    { price: 405, name: 'a Vegas night at the Bellagio', tier: 'snack', category: 'status' },
    { price: 400, name: 'a non-surgical cosmetic session', tier: 'snack', category: 'status' },
    { price: 379, name: 'one iPhone screen repair (out of warranty)', tier: 'snack', category: 'extraction' },
    { price: 349, name: 'an Apple Watch SE (entry model)', tier: 'snack', category: 'status' },
    { price: 275, name: 'a nice dinner for two', tier: 'snack', category: 'status' },
    { price: 260, name: 'a shot of Ozempic (per dose)', tier: 'snack', category: 'extraction', featured: true },
    { price: 255, name: 'an H&R Block in-person filing', tier: 'snack', category: 'extraction' },
    { price: 253, name: 'one year of weekly out-of-network ATM use', tier: 'snack', category: 'extraction' },
    { price: 250, name: 'a Roomba (basic)', tier: 'snack', category: 'status' },
    { price: 240, name: 'one year of ChatGPT Plus', tier: 'snack', category: 'extraction' },
    { price: 230, name: 'one year of Notion AI', tier: 'snack', category: 'extraction' },
    { price: 225, name: 'one year of overdraft fees (typical overdrafting household)', tier: 'snack', category: 'extraction', featured: true },
    { price: 220, name: 'one year of Xbox Game Pass Ultimate', tier: 'snack', category: 'extraction' },
    { price: 215, name: 'one year of Netflix (standard)', tier: 'snack', category: 'extraction' },
    { price: 210, name: 'a bag of designer pre-workout supplement', tier: 'snack', category: 'snack' },
    { price: 205, name: 'one year of LinkedIn Premium', tier: 'snack', category: 'extraction' },
    { price: 204, name: 'one year of Disney+ (no ads)', tier: 'snack', category: 'extraction' },
    { price: 200, name: 'a bottle of Dom Pérignon', tier: 'snack', category: 'status' },
    { price: 198, name: "a Cameo from someone you've heard of", tier: 'snack', category: 'snack' },
    { price: 195, name: 'an IV drip wellness session', tier: 'snack', category: 'status' },
    { price: 190, name: 'an hour with a private chef', tier: 'snack', category: 'status' },
    { price: 188, name: 'a TurboTax Self-Employed filing (federal + state)', tier: 'snack', category: 'extraction' },
    { price: 180, name: 'one year of checking account maintenance fees ($15/mo)', tier: 'snack', category: 'extraction' },
    { price: 179, name: 'AirPods (with ANC)', tier: 'snack', category: 'status' },
    { price: 178, name: 'a Costco run that got out of hand', tier: 'snack', category: 'snack' },
    { price: 175, name: 'one year of Audible', tier: 'snack', category: 'extraction' },
    { price: 170, name: 'a night at a bougie hot pot restaurant', tier: 'snack', category: 'status' },
    { price: 165, name: 'a pair of Lululemon leggings', tier: 'snack', category: 'status' },
    { price: 156, name: 'one Spotify Premium year', tier: 'snack', category: 'extraction' },
    { price: 155, name: 'a therapy session (full cash price)', tier: 'snack', category: 'extraction' },
    { price: 154, name: 'a Substack subscription you regret', tier: 'snack', category: 'extraction' },
    { price: 150, name: 'an emotional support animal certification (online)', tier: 'snack', category: 'snack' },
    { price: 145, name: 'an AI girlfriend monthly subscription', tier: 'snack', category: 'extraction' },
    { price: 135, name: 'a night at a Holiday Inn Express', tier: 'snack', category: 'status' },
    { price: 130, name: 'a paternity test', tier: 'snack', category: 'snack' },
    { price: 125, name: 'a concert nosebleed', tier: 'snack', category: 'status' },
    { price: 120, name: 'one Hulu year', tier: 'snack', category: 'extraction' },
    { price: 118, name: 'one Midjourney year', tier: 'snack', category: 'extraction' },
    { price: 105, name: 'a Global Entry application', tier: 'snack', category: 'extraction' },
    { price: 102, name: 'a Hamilton ticket (cheap)', tier: 'snack', category: 'status' },
    { price: 100, name: 'a DNA test (23andMe)', tier: 'snack', category: 'snack' },
    { price: 98, name: 'a Ring doorbell', tier: 'snack', category: 'status' },
    { price: 90, name: 'a private massage (60 min)', tier: 'snack', category: 'snack' },
    { price: 85, name: 'a pair of jeans', tier: 'snack', category: 'snack' },
    { price: 82, name: 'a TaskRabbit IKEA assembly', tier: 'snack', category: 'extraction' },
    { price: 80, name: 'TSA PreCheck', tier: 'snack', category: 'extraction' },
    { price: 78, name: 'one PlayStation Plus year', tier: 'snack', category: 'extraction' },
    { price: 77, name: 'a Vegas night at a budget hotel', tier: 'snack', category: 'status' },
    { price: 76, name: 'one ChatGPT API top-up (moderate use month)', tier: 'snack', category: 'extraction' },
    { price: 75, name: 'a Hello Fresh meal kit week', tier: 'snack', category: 'extraction' },
    { price: 72, name: 'a Lyft surge ride at 2am', tier: 'snack', category: 'extraction' },
    { price: 71, name: 'an Uber Eats order at 2am', tier: 'snack', category: 'extraction' },
    { price: 70, name: 'a personal trainer session', tier: 'snack', category: 'status' },
    { price: 68, name: 'a sensory deprivation tank float', tier: 'snack', category: 'status' },
    { price: 66, name: 'a bag of premium CBD gummies', tier: 'snack', category: 'snack' },
    { price: 63, name: 'one annual Costco membership', tier: 'snack', category: 'extraction' },
    { price: 60, name: 'one Ticketmaster service fee (pair of tickets)', tier: 'snack', category: 'extraction' },
    { price: 55, name: 'a tank of gas', tier: 'snack', category: 'snack' },
    { price: 52, name: 'an Equinox day pass', tier: 'snack', category: 'status' },
    { price: 50, name: "a Sam's Club membership", tier: 'snack', category: 'extraction' },
    { price: 49, name: 'a Tinder Platinum month', tier: 'snack', category: 'extraction' },
    { price: 48, name: 'one year of Robinhood Gold (paid annually)', tier: 'snack', category: 'extraction' },
    { price: 45, name: 'a cryotherapy session', tier: 'snack', category: 'status' },
    { price: 44, name: 'one Peloton All-Access Membership month', tier: 'snack', category: 'extraction' },
    { price: 42, name: 'one movie night for two (tickets + popcorn)', tier: 'snack', category: 'extraction' },
    { price: 40, name: 'a Steam game', tier: 'snack', category: 'snack' },
    { price: 39, name: 'a Cameo from a C-list celeb', tier: 'snack', category: 'snack' },
    { price: 38, name: 'a SoulCycle class', tier: 'snack', category: 'status' },
    { price: 36, name: 'one airline checked-bag fee (first bag, one way)', tier: 'snack', category: 'extraction' },
    { price: 35, name: 'one month of gym membership (typical chain)', tier: 'snack', category: 'extraction' },
    { price: 34, name: 'a pedicure', tier: 'snack', category: 'snack' },
    { price: 33, name: 'a DoorDash delivery (with all fees)', tier: 'snack', category: 'extraction' },
    { price: 32, name: 'an escape room (per person)', tier: 'snack', category: 'snack' },
    { price: 31, name: 'a Hinge premium month', tier: 'snack', category: 'extraction' },
    { price: 30, name: 'a Tinder Gold month', tier: 'snack', category: 'extraction' },
    { price: 29, name: 'an axe-throwing session', tier: 'snack', category: 'snack' },
    { price: 28, name: 'a wire transfer fee (typical domestic)', tier: 'snack', category: 'extraction' },
    { price: 27, name: 'a large delivery pizza', tier: 'snack', category: 'snack' },
    { price: 26.77, name: 'an overdraft fee (Bankrate 2025 average)', tier: 'snack', category: 'extraction' },
    { price: 26.5, name: 'a CrossFit class drop-in', tier: 'snack', category: 'status' },
    { price: 26, name: 'a Bumble Boost month', tier: 'snack', category: 'extraction' },
    { price: 25, name: 'an Uber ride across town', tier: 'snack', category: 'extraction' },
    { price: 24, name: 'an Erewhon smoothie', tier: 'snack', category: 'status' },
    { price: 23, name: 'a therapy session (typical copay)', tier: 'snack', category: 'extraction' },
    { price: 22, name: 'a Planet Fitness Black Card month', tier: 'snack', category: 'extraction' },
    { price: 21, name: 'a budget haircut (Great Clips tier)', tier: 'snack', category: 'snack' },
    { price: 20, name: 'a full-service car wash', tier: 'snack', category: 'snack' },
    { price: 18.5, name: 'a Claude Pro month', tier: 'snack', category: 'extraction' },
    { price: 18, name: 'a paperback book', tier: 'snack', category: 'snack' },
    { price: 17, name: 'an NSF (non-sufficient funds) fee', tier: 'snack', category: 'extraction' },
    { price: 15, name: 'a movie ticket', tier: 'snack', category: 'snack' },
    { price: 14, name: 'a Twitter Blue verification month', tier: 'snack', category: 'extraction' },
    { price: 13, name: 'a Chipotle burrito', tier: 'snack', category: 'snack' },
    { price: 12, name: 'one stadium beer', tier: 'snack', category: 'extraction' },
    { price: 11.5, name: 'a Botox unit', tier: 'snack', category: 'status', featured: true },
    { price: 11, name: 'a pack of cigarettes', tier: 'snack', category: 'snack' },
    { price: 10.5, name: 'an OnlyFans subscription (avg)', tier: 'snack', category: 'extraction' },
    { price: 9, name: 'one fast-food combo meal', tier: 'snack', category: 'extraction' },
    { price: 8, name: 'a round of mini golf', tier: 'snack', category: 'snack' },
    { price: 7.5, name: 'a Starbucks coffee', tier: 'snack', category: 'snack' },
    { price: 7, name: 'a Tinder profile boost', tier: 'snack', category: 'extraction' },
    { price: 6.5, name: 'an Adderall pill (10mg generic, cash retail without insurance)', tier: 'snack', category: 'extraction' },
    { price: 6, name: 'a Big Mac', tier: 'snack', category: 'snack' },
    { price: 5.5, name: 'a mid-tier scratch-off ticket', tier: 'snack', category: 'snack' },
    { price: 5, name: 'a Postmates delivery fee', tier: 'snack', category: 'extraction' },
    { price: 4.86, name: 'an ATM out-of-network fee (Bankrate 2025 average)', tier: 'snack', category: 'extraction' },
    { price: 4.75, name: 'a cheap cigar', tier: 'snack', category: 'snack' },
    { price: 4.5, name: 'a mechanical bull ride', tier: 'snack', category: 'snack' },
    { price: 4.25, name: 'a penny slot pull at max bet', tier: 'snack', category: 'snack' },
    { price: 4, name: 'a pre-rolled cone', tier: 'snack', category: 'snack' },
    { price: 3.75, name: 'a Four Loko', tier: 'snack', category: 'snack' },
    { price: 3.5, name: 'a greeting card', tier: 'snack', category: 'snack' },
    { price: 3.2, name: 'one gallon of gas', tier: 'snack', category: 'extraction' },
    { price: 3, name: 'one loaf of bread (name brand)', tier: 'snack', category: 'extraction' },
    { price: 2.85, name: 'a mini bottle of liquor (airplane bottle)', tier: 'snack', category: 'snack' },
    { price: 2.75, name: 'a can of Monster', tier: 'snack', category: 'snack' },
    { price: 2.6, name: 'a 5-Hour Energy shot', tier: 'snack', category: 'snack' },
    { price: 2.5, name: 'a Liquid Death', tier: 'snack', category: 'snack' },
    { price: 2.4, name: 'a White Claw', tier: 'snack', category: 'snack' },
    { price: 2.3, name: 'a Truly seltzer', tier: 'snack', category: 'snack' },
    { price: 2, name: 'a Powerball ticket', tier: 'snack', category: 'snack' },
    { price: 1.95, name: 'a scratch-off ticket (entry-tier)', tier: 'snack', category: 'snack' },
    { price: 1.85, name: 'a pickle from 7-Eleven cooler', tier: 'snack', category: 'snack' },
    { price: 1.75, name: 'an apple', tier: 'snack', category: 'snack' },
    { price: 1.65, name: 'a Slim Jim', tier: 'snack', category: 'snack' },
    { price: 1.5, name: 'a roll of toilet paper', tier: 'snack', category: 'snack' },
    { price: 1.45, name: 'a pickle (from a jar)', tier: 'snack', category: 'snack' },
    { price: 1.35, name: 'a Hot Wheels car', tier: 'snack', category: 'snack' },
    { price: 1.25, name: "a Reese's Cup", tier: 'snack', category: 'snack' },
    { price: 1.1, name: 'a Pop Rocks package', tier: 'snack', category: 'snack' },
    { price: 1.05, name: 'a claw machine attempt', tier: 'snack', category: 'snack' },
    { price: 1, name: 'an item from the $1 shop', tier: 'snack', category: 'snack' },
    { price: 0.98, name: 'a single cigarette', tier: 'snack', category: 'snack' },
    { price: 0.9, name: 'an onion', tier: 'snack', category: 'snack' },
    { price: 0.88, name: 'a pear', tier: 'snack', category: 'snack' },
    { price: 0.85, name: 'an AA battery', tier: 'snack', category: 'snack' },
    { price: 0.82, name: 'a potato', tier: 'snack', category: 'snack' },
    { price: 0.78, name: 'a tomato', tier: 'snack', category: 'snack' },
    { price: 0.75, name: 'an orange', tier: 'snack', category: 'snack' },
    { price: 0.73, name: 'a postage stamp', tier: 'snack', category: 'snack' },
    { price: 0.65, name: "a McDonald's chicken nugget", tier: 'snack', category: 'snack' },
    { price: 0.6, name: 'a pack of ramen', tier: 'snack', category: 'snack' },
    { price: 0.52, name: 'a lime', tier: 'snack', category: 'snack' },
    { price: 0.5, name: 'a condom (from a 12-pack)', tier: 'snack', category: 'snack' },
    { price: 0.48, name: 'a lemon', tier: 'snack', category: 'snack' },
    { price: 0.45, name: 'a disposable razor', tier: 'snack', category: 'snack' },
    { price: 0.42, name: 'nicotine gum', tier: 'snack', category: 'snack' },
    { price: 0.4, name: 'an arcade game token', tier: 'snack', category: 'snack' },
    { price: 0.38, name: 'a CBD gummy', tier: 'snack', category: 'snack' },
    { price: 0.35, name: 'an AAA battery', tier: 'snack', category: 'snack' },
    { price: 0.33, name: 'a Capri Sun', tier: 'snack', category: 'snack' },
    { price: 0.3, name: 'a banana', tier: 'snack', category: 'snack' },
    { price: 0.28, name: 'a gumball', tier: 'snack', category: 'snack' },
    { price: 0.25, name: 'a single egg', tier: 'snack', category: 'snack' },
    { price: 0.23, name: 'a nicotine pouch (Zyn)', tier: 'snack', category: 'snack' },
    { price: 0.22, name: 'a Bic pen', tier: 'snack', category: 'snack' },
    { price: 0.2, name: 'a penny slot pull (min bet)', tier: 'snack', category: 'snack' },
    { price: 0.18, name: 'a bowl of cooked rice', tier: 'snack', category: 'snack' },
    { price: 0.16, name: 'a claw machine prize (cost basis)', tier: 'snack', category: 'snack' },
    { price: 0.15, name: 'a single tortilla', tier: 'snack', category: 'snack' },
    { price: 0.14, name: 'a Snickers fun size', tier: 'snack', category: 'snack' },
    { price: 0.13, name: 'the lettuce from a Big Mac', tier: 'snack', category: 'snack' },
    { price: 0.12, name: 'a carrot', tier: 'snack', category: 'snack' },
    { price: 0.11, name: 'a donut hole', tier: 'snack', category: 'snack' },
    { price: 0.095, name: 'a Tootsie Pop', tier: 'snack', category: 'snack' },
    { price: 0.09, name: 'a Dum Dum lollipop', tier: 'snack', category: 'snack' },
    { price: 0.085, name: 'a pair of wooden chopsticks', tier: 'snack', category: 'snack' },
    { price: 0.08, name: 'a slice of bread', tier: 'snack', category: 'snack' },
    { price: 0.075, name: 'a soft pretzel bite', tier: 'snack', category: 'snack' },
    { price: 0.07, name: 'a tea bag', tier: 'snack', category: 'snack' },
    { price: 0.065, name: 'a Tylenol tablet', tier: 'snack', category: 'snack' },
    { price: 0.06, name: 'a melatonin gummy', tier: 'snack', category: 'snack' },
    { price: 0.055, name: 'a Listerine strip', tier: 'snack', category: 'snack' },
    { price: 0.05, name: 'a pencil', tier: 'snack', category: 'snack' },
    { price: 0.048, name: 'a Solo cup', tier: 'snack', category: 'snack' },
    { price: 0.045, name: 'a stick of gum', tier: 'snack', category: 'snack' },
    { price: 0.04, name: 'a paper plate', tier: 'snack', category: 'snack' },
    { price: 0.038, name: 'a plastic fork', tier: 'snack', category: 'snack' },
    { price: 0.035, name: 'a clothes peg', tier: 'snack', category: 'snack' },
    { price: 0.033, name: 'a Bandaid', tier: 'snack', category: 'snack' },
    { price: 0.03, name: 'a ketchup packet', tier: 'snack', category: 'snack' },
    { price: 0.028, name: "a Hershey's Kiss", tier: 'snack', category: 'snack' },
    { price: 0.026, name: 'a single Altoid mint', tier: 'snack', category: 'snack' },
    { price: 0.024, name: 'a Tums tablet', tier: 'snack', category: 'snack' },
    { price: 0.022, name: 'a paper fortune from a fortune cookie', tier: 'snack', category: 'snack', featured: true },
    { price: 0.02, name: 'an Ibuprofen tablet', tier: 'snack', category: 'snack' },
    { price: 0.018, name: 'a single Pringle', tier: 'snack', category: 'snack' },
    { price: 0.016, name: 'a single Dorito', tier: 'snack', category: 'snack' },
    { price: 0.014, name: 'a sugar packet', tier: 'snack', category: 'snack' },
    { price: 0.013, name: 'a plastic spoon', tier: 'snack', category: 'snack' },
    { price: 0.012, name: 'a Popsicle stick', tier: 'snack', category: 'snack' },
    { price: 0.011, name: 'a Tootsie Roll mini', tier: 'snack', category: 'snack' },
    { price: 0.0105, name: 'a bobby pin', tier: 'snack', category: 'snack' },
    { price: 0.01, name: 'a thumbtack', tier: 'snack', category: 'snack' },
    { price: 0.0095, name: 'a plastic straw', tier: 'snack', category: 'snack' },
    { price: 0.009, name: 'a saltine cracker', tier: 'snack', category: 'snack' },
    { price: 0.0085, name: 'a single pretzel stick', tier: 'snack', category: 'snack' },
    { price: 0.008, name: 'a single napkin', tier: 'snack', category: 'snack' },
    { price: 0.0075, name: 'a single coffee filter', tier: 'snack', category: 'snack' },
    { price: 0.007, name: 'a single sheet of rolling paper', tier: 'snack', category: 'snack' },
    { price: 0.0065, name: 'a paperclip', tier: 'snack', category: 'snack' },
    { price: 0.006, name: 'a square of aluminum foil', tier: 'snack', category: 'snack' },
    { price: 0.0055, name: 'a single Cheeto', tier: 'snack', category: 'snack' },
    { price: 0.005, name: 'a Q-tip', tier: 'snack', category: 'snack' },
    { price: 0.0045, name: 'a sheet of printer paper', tier: 'snack', category: 'snack' },
    { price: 0.004, name: 'a Tic Tac', tier: 'snack', category: 'snack' },
    { price: 0.0038, name: 'a single match', tier: 'snack', category: 'snack' },
    { price: 0.0035, name: 'a rubber band', tier: 'snack', category: 'snack' },
    { price: 0.003, name: 'a sheet of toilet paper', tier: 'snack', category: 'snack' },
    { price: 0.0028, name: 'a single Skittle', tier: 'snack', category: 'snack' },
    { price: 0.0025, name: 'a toothpick', tier: 'snack', category: 'snack' },
    { price: 0.0023, name: 'a Goldfish cracker', tier: 'snack', category: 'snack' },
    { price: 0.002, name: 'a single M&M', tier: 'snack', category: 'snack' },
    { price: 0.0018, name: 'a single coffee bean', tier: 'snack', category: 'snack' },
    { price: 0.0016, name: 'a single sprinkle (large)', tier: 'snack', category: 'snack' },
    { price: 0.0014, name: 'a sunflower seed', tier: 'snack', category: 'snack' },
    { price: 0.0012, name: 'a single Cheerio', tier: 'snack', category: 'snack' },
    { price: 0.001, name: 'a single staple', tier: 'snack', category: 'snack' },
    { price: 0.0008, name: 'a Froot Loop', tier: 'absurd_floor', category: 'snack' },
    { price: 0.0007, name: 'a pinch of pepper', tier: 'absurd_floor', category: 'snack' },
    { price: 0.0006, name: 'a single coffee ground', tier: 'absurd_floor', category: 'snack' },
    { price: 0.00055, name: 'a single sprinkle (small)', tier: 'absurd_floor', category: 'snack' },
    { price: 0.0005, name: 'a single eyelash', tier: 'absurd_floor', category: 'snack' },
    { price: 0.00045, name: 'a piece of confetti', tier: 'absurd_floor', category: 'snack' },
    { price: 0.0004, name: 'a grain of sugar', tier: 'absurd_floor', category: 'snack' },
    { price: 0.00035, name: 'a grain of rice', tier: 'absurd_floor', category: 'snack' },
    { price: 0.0003, name: 'a single mustard seed', tier: 'absurd_floor', category: 'snack' },
    { price: 0.00025, name: 'a poppy seed', tier: 'absurd_floor', category: 'snack' },
    { price: 0.0002, name: 'a sesame seed', tier: 'absurd_floor', category: 'snack' },
    { price: 0.00015, name: 'a speck of dust', tier: 'absurd_floor', category: 'snack' },
    { price: 0.00012, name: 'a broken rubber band', tier: 'absurd_floor', category: 'snack' },
    { price: 0.0001, name: 'a grain of fine sand', tier: 'absurd_floor', category: 'snack' },
    { price: 7e-05, name: 'a crumb from the bottom of the bag', tier: 'void', category: 'snack' },
    { price: 5e-05, name: "a dropped McDonald's chip", tier: 'void', category: 'snack' },
    { price: 3.5e-05, name: 'a flake of dandruff', tier: 'void', category: 'snack' },
    { price: 2.5e-05, name: "a popcorn kernel that didn't pop", tier: 'void', category: 'snack' },
    { price: 2e-05, name: 'a squeezed-out lime wedge', tier: 'void', category: 'snack' },
    { price: 1.5e-05, name: "a fingernail clipping", tier: 'void', category: 'snack' },
    { price: 1e-05, name: 'a popped bubble-wrap bubble', tier: 'void', category: 'snack' },
    { price: 7.5e-06, name: 'a used cotton swab', tier: 'void', category: 'snack' },
    { price: 5e-06, name: 'a single belly button lint', tier: 'void', category: 'snack' },
    { price: 3e-06, name: 'a strand of shed cat hair', tier: 'void', category: 'snack' },
    { price: 2e-06, name: 'a used tooth floss string', tier: 'void', category: 'snack' },
    { price: 1.5e-06, name: 'a burnt match head', tier: 'void', category: 'snack' },
    { price: 1e-06, name: 'a single toothbrush bristle', tier: 'void', category: 'snack' },
];

const TIER_META = {
    heavyweight:  { cls: 'tier-heavy',  text: '🍔 Heavyweight Tier — $1,000+',        emoji: '💎' },
    snack:        { cls: 'tier-snack',  text: '🏠 Real Life Tier — $0.001 to $1,000', emoji: '🏠' },
    absurd_floor: { cls: 'tier-absurd', text: '🤡 Absurd Floor — $0.0001 to $0.001',  emoji: '🏖️' },
    void:         { cls: 'tier-dust',   text: '🕳 The Gutter — stuff so cheap it fell through the price floor',  emoji: '🕳️' },
};
